import React from 'react';

import Head from 'next/head';
import Image from 'next/image';
import { useRef } from 'react';

import Header from '../components/header';
import Footer from '../components/footer';
import Button from '../components/button';
import ArrowButton from '../components/arrowButton';
import Container from '../components/container';
import Card from '../components/card';
import Product from '../components/product';
import FeatureItem from '../components/featureItem';
import OtherFeatureItem from '../components/otherFeatureItem';
import useScrollTop from '../hooks/useScrollTop';
import { motion, useViewportScroll } from 'framer-motion';

const Index = () => {
	const scrollTop = useScrollTop();

	const featureRef = useRef(null);
	const othersRef = useRef(null);

	console.log('scrollTop', scrollTop);

	const [lastYPos, setLastYPos] = React.useState(0);
	const [shouldShowActions, setShouldShowActions] = React.useState(true);

	React.useEffect(() => {
		function handleScroll() {
			const yPos = window.scrollY;
			const isScrollingUp = lastYPos > yPos;

			setShouldShowActions(isScrollingUp);
			setLastYPos(yPos);
		}

		window.addEventListener('scroll', handleScroll, false);

		return () => {
			window.removeEventListener('scroll', handleScroll, false);
		};
	}, [lastYPos]);

	const slide_animate = {
		hidden: {
			opacity: 0,
			pathLength: 0,
			fill: 'rgba(255, 255, 255, 0)',
		},
		visible: {
			opacity: 1,
			pathLength: 1,
			fill: '#FF5B79',
		},
	};

	return (
		<div>
			<Head>
				<title>Home</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='w-fill bg-black min-h-screen py-12 bg-hero bg-no-repeat bg-right-top'>
				<Container>
					<Header />

					<div className='flex flex-col space-y-32'>
						<div className='section-1 grid md:grid-cols-2 xs:grid-cols-1 gap-4'>
							<div className='section-1-left h-full flex flex-col justify-center'>
								<div className='text-white text-6xl mb-6 font-black animate__animated animate__fadeInLeft animate__delay-1s'>
									Casper Next Gen Crypto
								</div>
								<div className='text-white text-base mb-6 animate__animated animate__fadeInLeft animate__delay-2s'>
									In search for cute little puppy, Captain Sem has come back
									from his tragic death. With his hogwarts certified power he
									promise to be a hero for all of ghostkind.
								</div>
								<div className='flex items-center space-x-4 animate__animated animate__fadeInLeft animate__delay-3s'>
									<Button>Trade Now</Button>
									<ArrowButton>Exchange Rates</ArrowButton>
								</div>
							</div>

							<div className='section-1-right animate__animated animate__bounceInRight animate__delay-4s'>
								<div className='animate__animated animate__wobble animate__delay-5s'>
									<Image
										src='/img/ghost.png'
										height={2000}
										width={2000}
										alt='section-1-img'
									/>
								</div>
							</div>
						</div>

						<div className='section-2'>
							<div className='flex items-center justify-between mb-12'>
								<div className='text-white text-3xl font-black'>
									Explore Products
								</div>
								<ArrowButton>View All Products</ArrowButton>
							</div>

							<div className='grid md:grid-cols-2 xs:grid-cols-1 gap-12'>
								<Card
									title='Card'
									text='In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind.'
									icon='/img/products/trade.svg'
									buttonText='button'
									className={[
										'delay-100 duration-1000',
										scrollTop > 300
											? 'mb-0 mt-0 opacity-1'
											: 'mt-20 -mb-20 opacity-0',
									].join(' ')}
								/>
								<Card
									title='Card'
									text='In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind.'
									icon='/img/products/farm.svg'
									buttonText='button'
									className={[
										'delay-300 duration-1000',
										scrollTop > 300
											? 'mb-0 mt-0 opacity-1'
											: 'mt-20 -mb-20 opacity-0',
									].join(' ')}
								/>
								<Card
									title='Card'
									text='In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind.'
									icon='/img/products/api.svg'
									buttonText='button'
									className={[
										'delay-100 duration-1000',
										scrollTop > 500
											? 'mb-0 mt-0 opacity-1'
											: 'mt-20 -mb-20 opacity-0',
									].join(' ')}
								/>
								<Card
									title='Card'
									text='In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind.'
									icon='/img/products/token.svg'
									buttonText='button'
									className={[
										'delay-300 duration-1000',
										scrollTop > 500
											? 'mb-0 mt-0 opacity-1'
											: 'mt-20 -mb-20 opacity-0',
									].join(' ')}
								/>
							</div>

							<div className='text-white text-3xl mt-12'>
								WE BELIEVE IN THE POTENTIAL OF FAST &amp; FEELESS BLOCKCHAIN
								&amp; ARE READY TO PRESENT THE UNIFIED ECOSYSTEM BUILT ON
								Casper→SO #JOINTHECASPER
							</div>
						</div>

						<div className='section-3 text-white'>
							<div className='text-3xl font-black mb-12'>Why Casper</div>
							<div className='grid grid-cols-2 gap-6'>
								<div className='flex flex-col space-y-6'>
									<div className='text-xl font-bold mb-6'>Casper</div>
									<FeatureItem
										className={[
											'duration-1000 delay-100',
											scrollTop > 1400 ? 'ml-0 opacity-1' : '-ml-20 opacity-0',
										].join(' ')}
									>
										Secure and scalable
									</FeatureItem>
									<FeatureItem
										className={[
											'duration-1000 delay-300',
											scrollTop > 1400 ? 'ml-0 opacity-1' : '-ml-20 opacity-0',
										].join(' ')}
									>
										Secure and scalable
									</FeatureItem>
									<FeatureItem
										className={[
											'duration-1000 delay-500',
											scrollTop > 1400 ? 'ml-0 opacity-1' : '-ml-20 opacity-0',
										].join(' ')}
									>
										Secure and scalable
									</FeatureItem>
									<FeatureItem
										className={[
											'duration-1000 delay-700',
											scrollTop > 1400 ? 'ml-0 opacity-1' : '-ml-20 opacity-0',
										].join(' ')}
									>
										Secure and scalable
									</FeatureItem>
								</div>

								<div className='flex flex-col space-y-6'>
									<div className='text-xl font-bold mb-6'>Others</div>
									<OtherFeatureItem
										className={[
											'duration-1000 delay-900',
											scrollTop > 1400 ? 'ml-0 opacity-1' : '-ml-20 opacity-0',
										].join(' ')}
									>
										Secure and scalable
									</OtherFeatureItem>
									<OtherFeatureItem
										className={[
											'duration-1000 delay-1100',
											scrollTop > 1400 ? 'ml-0 opacity-1' : '-ml-20 opacity-0',
										].join(' ')}
									>
										Secure and scalable
									</OtherFeatureItem>
									<OtherFeatureItem
										className={[
											'duration-1000 delay-1300',
											scrollTop > 1400 ? 'ml-0 opacity-1' : '-ml-20 opacity-0',
										].join(' ')}
									>
										Secure and scalable
									</OtherFeatureItem>
									<OtherFeatureItem
										className={[
											'duration-1000 delay-1500',
											scrollTop > 1400 ? 'ml-0 opacity-1' : '-ml-20 opacity-0',
										].join(' ')}
									>
										Secure and scalable
									</OtherFeatureItem>
								</div>
							</div>
						</div>

						<motion.div
							className='animate-image'
							className='actions'
							initial={{ opacity: 0 }}
							animate={{ opacity: shouldShowActions ? 1 : 0 }}
							transition={{ opacity: { duration: 0.2 } }}
						>
							<motion.svg
								className='item'
								viewBox='0 0 100 100'
								xmlns='http://www.w3.org/2000/svg'
							>
								<motion.path
									d='M19.0209 249.742C17.9789 254.791 14.5576 259.595 15.6909 265.085C15.9346 266.267 15.2552 267.029 14.6276 267.973C13.8904 269.082 14.195 279.011 13.9513 280.404C13.2719 284.306 17.2812 287.819 15.5233 291.241C13.4303 295.308 14.8561 298.516 15.4655 302.419C16.9552 311.973 20.1633 320.701 25.693 330.253C25.3974 326.84 25.5224 324.616 27.1523 322.932C25.9093 322.213 24.5809 322.749 23.9077 321.265C25.5163 314.322 21.7019 307.811 21.0987 300.801C20.5289 294.263 18.8381 287.789 18.966 281.062C19.1671 270.627 19.0209 260.183 19.0209 249.742ZM119.317 392.225C122.404 394.227 124.5 397.002 127.449 399.071C134.508 404.018 142.402 407.147 149.969 410.98C153.187 412.607 156.794 411.909 158.573 409.036C164.529 399.412 170.875 389.989 174.339 379.033C175.96 373.906 177.867 368.873 179.586 363.772C181.414 358.356 181.999 352.628 183.287 347.086C184.53 341.727 183.787 335.984 185.018 330.354C186.712 322.613 182.428 314.92 183.543 307.002C180.515 304.507 182.523 300.881 181.499 297.886C179.257 291.33 177.252 284.691 175.244 278.056C171.792 266.622 166.043 256.126 159.426 246.496C154.308 239.047 148.592 231.677 141.232 225.706C136.055 221.504 130.882 217.464 125.015 214.503C115.189 209.537 105.065 205.248 93.6221 206.094C91.9678 206.216 90.2921 206.229 88.6439 206.091C76.951 205.123 71.3696 211.786 65.4073 220.112C62.3424 224.393 61.4285 229.861 57.3612 233.456C57.934 234.702 60.4688 235.604 58.2996 237.408C56.9895 238.495 57.154 239.827 57.2759 241.14C57.5105 243.687 54.2262 241.7 54.1165 243.665C57.1906 246.642 55.7282 248.848 53.0289 250.84C52.4135 250.338 51.856 249.881 50.8262 249.04C50.159 254.752 50.424 260.023 49.2023 265.303C47.4414 272.94 50.1163 280.868 51.1735 288.503C52.1637 295.693 53.623 303.267 57.154 310.009C57.2759 310.24 56.17 311.118 55.6003 311.73C60.941 315.429 62.5984 321.671 65.2977 326.866C70.2667 336.423 75.0621 345.928 82.7183 353.642C83.8943 354.825 83.3032 356.412 83.946 357.274C85.4572 359.306 85.1281 361.789 86.1335 363.919H89.2929C91.2579 364.659 90.283 366.804 91.7332 368.016C92.9549 369.037 94.7372 368.699 95.8004 371.057C97.3969 374.594 100.958 377.458 104.17 379.993C107.289 382.454 108.02 387.539 113.282 387.771C115.086 387.85 115.037 390.82 116.222 392.225H119.317ZM125.973 458.847C123.529 463.636 118.323 461.876 114.545 463.374C111.894 464.419 108.345 466.875 105.493 465.175C102.435 463.356 100.311 466.138 97.5905 465.498C95.7077 465.053 93.2795 464.532 91.4698 466.692C90.9885 467.268 89.127 467.387 88.3989 466.927C86.4825 465.72 84.8404 464.121 83.052 466.966C78.7075 464.243 73.6684 466.004 69.0528 464.776C63.7425 463.365 58.3927 461.946 52.8478 461.784C51.2697 460.209 49.7006 458.643 48.1377 457.077C46.52 459.018 44.7255 459.307 42.4466 458.073C34.105 453.546 24.6818 450.889 17.0957 445.223C11.3711 440.948 4.86957 437.774 -0.139084 432.32C-5.40974 426.58 -11.9783 422.105 -17.4744 416.481C-25.42 408.349 -32.1195 399.167 -39.7574 390.786C-40.6257 386.383 -44.4278 383.961 -46.6732 380.494C-49.1014 376.75 -52.2912 373.615 -54.4634 369.618C-56.5686 365.742 -58.7378 361.782 -61.9459 358.555C-63.2316 357.261 -62.1318 356.103 -60.7425 354.899C-62.9087 352.103 -66.5798 350.902 -67.7467 346.661C-68.682 343.27 -72.1917 340.443 -74.2848 337.004C-80.4603 326.846 -86.2275 316.503 -91.4372 305.837C-93.3444 301.928 -94.3955 297.455 -96.912 294.034C-99.4742 290.555 -99.7576 286.32 -102.161 282.828C-104.602 279.285 -106.32 275.157 -107.856 271.099C-112.477 258.885 -118.312 247.204 -122.933 234.954C-127.814 222.015 -133.033 209.222 -137.332 196.048C-138.831 191.451 -140.945 187.058 -142.346 182.333C-144.028 176.663 -145.396 170.88 -147.355 165.311C-149.241 159.949 -151.861 154.889 -152.303 149.03C-152.403 147.772 -154.371 146.44 -153.744 144.743C-153.192 143.257 -156.659 142.906 -154.411 140.764C-153.345 139.753 -156.199 138.717 -156.87 137.398C-157.86 135.463 -157.302 133.303 -157.838 131.186C-160.44 120.891 -163.926 110.847 -165.741 100.284C-166.765 94.3247 -167.499 88.0761 -170.147 82.2327C-171.673 78.8631 -169.827 74.2566 -172.084 70.5794C-171.009 64.2942 -174.781 58.4507 -173.766 52.1564C-173.486 50.4229 -176.063 49.0062 -173.949 46.703C-173.151 45.8347 -176.051 43.4065 -175.503 40.9083C-175.037 38.797 -175.405 36.4968 -175.405 34.2819C-175.405 32.067 -175.329 29.849 -175.42 27.6372C-175.658 21.8791 -173.912 17.038 -170.64 12.1055C-167.706 7.6879 -164.654 3.78822 -160.367 0.753785C-158.829 -0.33386 -157.388 -0.0535703 -155.873 0.461309C-153.914 3.47442 -157.013 5.36333 -157.525 7.81281C-157.933 9.75656 -160.276 10.8594 -159.541 13.6562C-159.081 15.4202 -161.269 17.3731 -158.896 19.5911C-156.623 21.7176 -161.665 23.5121 -160.05 26.3454C-159.41 26.4795 -158.652 26.6349 -157.781 26.8176C-157.683 26.9121 -157.305 27.1223 -157.32 27.3021C-157.738 32.7159 -156.169 37.8891 -155.459 43.1628C-155.27 44.5338 -156.586 44.8902 -157.162 45.9535C-156.184 46.2917 -155.218 46.6268 -154.256 46.9589C-153.506 48.8326 -153.32 50.6057 -155.173 52.0924C-154.999 52.458 -154.926 52.9973 -154.624 53.1984C-152.248 54.7796 -152.668 57.3174 -152.01 59.6267C-148.534 71.7858 -147.242 84.5298 -142.17 96.2502C-142.148 103.477 -138.185 109.57 -136.329 116.276C-135.172 120.459 -133.804 124.715 -132.71 128.831C-131.58 133.078 -127.531 136.517 -128.877 141.426C-124.996 147.613 -124.274 155.032 -121.093 161.463C-118.805 166.094 -118.01 171.194 -115.899 175.944C-113.866 180.517 -112.34 185.595 -110.393 190.269C-107.45 197.343 -105.272 204.731 -101.397 211.507C-99.3036 215.175 -97.4696 219.328 -96.0316 223.364C-89.3534 242.059 -79.8357 259.357 -70.7233 276.869C-67.9996 282.1 -64.1212 286.847 -63.0854 292.791C-62.5461 295.889 -59.3776 297.026 -58.8445 300.258C-58.4697 302.519 -55.4048 304.21 -54.3994 306.528C-53.2478 309.191 -51.7794 311.537 -50.2865 313.983C-47.8949 317.907 -44.894 321.81 -45.7745 326.676C-44.373 327.852 -44.3304 326.316 -43.6662 326.2C-38.6454 331.047 -38.4229 331.797 -40.5708 336.824C-39.8061 337.552 -39.0384 338.286 -38.3072 338.984C-37.6704 338.448 -37.1038 337.966 -36.6376 337.573C-31.3731 341.698 -27.9913 346.613 -29.2465 353.407C-27.3698 354.113 -27.0316 351.64 -25.1915 352.52C-21.2796 357.928 -17.645 364.067 -12.8892 369.155C-9.34901 372.942 -5.75705 376.759 -2.00056 380.381C1.98442 384.229 5.85059 388.199 9.7655 392.117C13.6835 396.035 17.2114 400.465 21.6016 403.755C29.5289 409.696 37.3679 415.719 46.0051 420.822C52.9666 424.932 60.2054 428.152 67.4777 431.324C72.3889 433.466 77.891 434.526 83.2409 435.269C85.9006 435.638 88.3714 436.138 90.8605 437.042C91.7806 437.375 93.0572 437.387 93.8097 436.232C94.2149 434.218 92.6794 432.841 91.4059 432.354C83.9569 429.505 78.7075 423.744 73.0103 418.668C67.435 413.702 62.2558 408.27 57.11 402.85C48.7074 394.009 41.5662 384.26 35.5247 373.603C31.7073 366.87 27.3963 360.453 23.8896 353.489C18.4362 342.664 13.8906 331.544 10.8684 319.842C10.451 318.212 8.5377 317.258 9.10742 315.604C9.93611 313.212 5.86581 311.512 7.76385 309.87C10.3718 307.616 6.5574 306.952 7.25813 305.136C7.88574 303.5 7.52623 301.574 5.8719 299.938C4.81778 298.896 6.47211 297.605 7.42874 296.55C3.81239 294.908 4.45523 291.14 4.27548 288.529C3.71185 280.26 3.23048 271.812 4.3486 263.656C5.15291 257.761 5.66168 251.655 7.44397 245.9C9.18663 240.276 11.6879 234.878 13.2356 229.211C14.305 225.29 17.0256 222.457 18.5733 218.941C20.0753 215.529 22.7685 212.747 24.2065 209.627C26.3117 205.054 30.772 203.336 33.4347 199.546C35.9025 196.036 40.5273 194.077 44.3233 192.015C48.9695 189.489 53.8258 186.878 58.9776 185.382C63.9253 183.947 68.6933 182.031 73.8147 180.931C80.5538 179.481 87.1284 177.763 94.0991 177.784C97.2067 177.793 100.007 175.758 103.388 176.114C107.614 176.559 111.791 176.178 116.053 177.674C119.95 179.042 124.319 178.198 128.66 179.237C144.792 183.097 147.665 182.847 162.944 190.933C165.204 192.127 166.554 195.119 169.655 194.723C178.698 204.558 189.656 212.64 196.822 224.187C205.539 238.232 212.229 253.179 216.832 269.079C218.118 273.524 220.674 277.591 220.698 282.46C223.346 273.719 217.161 266.298 216.637 256.03C220.799 263.297 221.853 269.53 223.34 275.526C225.308 283.499 226.777 291.53 227.081 299.874C227.218 303.652 228.166 307.68 228.47 311.656C228.742 315.232 225.972 318.054 226.63 321.795C227.197 325.018 227.368 328.567 226.636 331.718C224.23 342.043 222.234 352.441 219.264 362.677C216.068 373.688 211.12 383.748 205.941 393.738C202.565 400.245 198.854 406.817 193.084 411.646C190.735 413.605 190.442 417.407 186.887 418.208C186.677 418.257 187.049 419.765 186.195 420.332C184.374 421.541 185.696 423.333 184.977 424.786C193.916 427.211 202.608 428.865 211.239 430.766C217.725 432.195 224.287 432.195 230.758 433.496C237.147 434.785 244.084 434.462 250.625 433.618C260.213 432.381 269.947 431.464 279.236 428.573C288.306 425.749 296.678 421.206 305.261 417.194C307.951 415.935 308.718 412.072 312.323 412.176C317.371 405.153 326.188 402.171 330.672 394.204C333.36 389.424 338.35 385.999 341.707 381.323C346.597 374.52 350.923 367.357 355.771 360.548C359.704 355.024 362.516 348.855 365.971 343.094C371.052 334.615 374.456 325.039 377.822 315.662C379.723 310.367 382.154 305.279 383.486 299.692C385.365 291.779 388.528 284.163 387.931 275.809C387.684 272.394 385.652 269.381 386.124 265.673C386.407 263.458 387.465 262.285 388.793 260.972C391.157 264.686 391.919 269.289 396.132 273.253C395.045 269.953 400.029 268.841 396.653 265.118C395.069 263.367 396.863 259.357 393.963 257.206C395.297 256.094 396.141 255.391 397.835 253.977C398.755 255.214 400.096 256.582 400.882 258.215C401.552 259.61 401.251 261.658 404.422 260.689C402.265 257.752 402.96 254.522 402.981 251.019C406.457 251.159 409.598 250.163 412.389 252.268C413.449 251.604 412.188 249.974 413.72 249.508C415.058 250.936 416.999 251.975 417.873 254.068C418.601 255.814 419.494 257.493 420.341 259.263C422.138 257.803 420.185 255.689 421.855 254.455C423.601 257.039 424.661 259.68 424.569 262.955C424.356 270.983 424.262 279.029 424.6 287.048C424.777 291.179 423.159 294.887 422.559 298.784C421.261 307.147 419.043 315.513 415.999 323.416C413.431 330.079 412.139 337.33 407.883 343.313C403.359 359.113 392.135 371.132 384.183 384.994C382.243 388.382 379.184 391.343 376.506 394.21C366.409 405.013 357.306 416.782 346.119 426.544C330.685 440.013 313.8 451.374 294.896 459.326C287.127 462.591 278.935 464.974 270.718 467.213C264.734 468.843 258.431 469.218 252.697 471.783C252.234 471.99 251.652 471.935 251.128 472.002C241.583 473.188 205.234 474.955 197.84 473.489C189.827 471.902 181.653 471.469 173.723 469.605C166.188 467.829 158.739 465.672 151.248 463.71C150.727 463.576 149.971 463.923 149.615 463.658C142.729 458.518 134.805 458.287 125.973 458.847Z'
									variants={shouldShowActions && slide_animate}
									initial='hidden'
									animate='visible'
									transition={{
										default: { duration: 2, ease: 'easeInOut' },
										fill: { duration: 2, ease: [1, 0, 0.8, 1] },
									}}
								/>
							</motion.svg>
						</motion.div>

						<div className='section-4 flex flex-col space-y-12'>
							<Product
								direction='left'
								image='/img/products/thumbnail.svg'
								title='Casper Tracker'
								text='In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind.'
								buttonText='Go to Tracker'
								classNameImage={[
									'delay-100 duration-1000',
									scrollTop > 1800
										? 'mb-0 mt-0 opacity-1'
										: 'mt-30 -mb-30 opacity-0',
								].join(' ')}
								classNameDesc={[
									'delay-300 duration-1000',
									scrollTop > 1800
										? 'mb-0 mt-0 opacity-1'
										: 'mt-30 -mb-30 opacity-0',
								].join(' ')}
							/>
							<Product
								direction='right'
								image='/img/products/thumbnail.svg'
								title='Casper Farm'
								text='In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind.'
								buttonText='Go to Farm'
								classNameImage={[
									'delay-500 duration-1000',
									scrollTop > 2200
										? 'mb-0 mt-0 opacity-1'
										: 'mt-30 -mb-30 opacity-0',
								].join(' ')}
								classNameDesc={[
									'delay-700 duration-1000',
									scrollTop > 2200
										? 'mb-0 mt-0 opacity-1'
										: 'mt-30 -mb-30 opacity-0',
								].join(' ')}
							/>
							<Product
								direction='left'
								image='/img/products/thumbnail.svg'
								title='Casper Api'
								text='In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind.'
								buttonText='Go to Api'
								classNameImage={[
									'delay-500 duration-1000',
									scrollTop > 2600
										? 'mb-0 mt-0 opacity-1'
										: 'mt-30 -mb-30 opacity-0',
								].join(' ')}
								classNameDesc={[
									'delay-700 duration-1000',
									scrollTop > 2600
										? 'mb-0 mt-0 opacity-1'
										: 'mt-30 -mb-30 opacity-0',
								].join(' ')}
							/>
							<Product
								direction='right'
								image='/img/products/thumbnail.svg'
								title='Casper Token'
								text='In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind.'
								buttonText='Go to Token'
								classNameImage={[
									'delay-500 duration-1000',
									scrollTop > 3000
										? 'mb-0 mt-0 opacity-1'
										: 'mt-30 -mb-30 opacity-0',
								].join(' ')}
								classNameDesc={[
									'delay-700 duration-1000',
									scrollTop > 3000
										? 'mb-0 mt-0 opacity-1'
										: 'mt-30 -mb-30 opacity-0',
								].join(' ')}
							/>
						</div>
					</div>

					<Footer />
				</Container>
			</div>
		</div>
	);
};

export default Index;
