import Head from "next/head";
import Image from "next/image";
import { useRef } from "react";

import Header from "../components/header";
import Footer from "../components/footer";
import Button from "../components/button";
import ArrowButton from "../components/arrowButton";
import Container from "../components/container";
import Card from "../components/card";
import Product from "../components/product";
import FeatureItem from "../components/featureItem";
import OtherFeatureItem from "../components/otherFeatureItem";
import useScrollTop from "../hooks/useScrollTop";

const Index = () => {
  const scrollTop = useScrollTop();

  const featureRef = useRef(null);
  const othersRef = useRef(null);

  console.log("scrollTop", scrollTop);

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-fill bg-black min-h-screen py-12 bg-hero bg-no-repeat bg-right-top">
        <Container>
          <Header />

          <div className="flex flex-col space-y-32">
            <div className="section-1 grid md:grid-cols-2 xs:grid-cols-1 gap-4">
              <div className="section-1-left h-full flex flex-col justify-center">
                <div className="text-white text-6xl mb-6 font-black animate__animated animate__fadeInLeft animate__delay-1s">
                  Casper Next Gen Crypto
                </div>
                <div className="text-white text-base mb-6 animate__animated animate__fadeInLeft animate__delay-2s">
                  In search for cute little puppy, Captain Sem has come back
                  from his tragic death. With his hogwarts certified power he
                  promise to be a hero for all of ghostkind.
                </div>
                <div className="flex items-center space-x-4 animate__animated animate__fadeInLeft animate__delay-3s">
                  <Button>Trade Now</Button>
                  <ArrowButton>Exchange Rates</ArrowButton>
                </div>
              </div>

              <div className="section-1-right animate__animated animate__bounceInRight animate__delay-4s">
                <div className="animate__animated animate__wobble animate__delay-5s">
                
                <Image
                  src="/img/ghost.png"
                  height={2000}
                  width={2000}
                  alt="section-1-img"
                />
                </div>
              </div>
            </div>

            <div className="section-2">
              <div className="flex items-center justify-between mb-12">
                <div className="text-white text-3xl font-black">
                  Explore Products
                </div>
                <ArrowButton>View All Products</ArrowButton>
              </div>

              <div className="grid md:grid-cols-2 xs:grid-cols-1 gap-12">
                <Card
                  title="Card"
                  text="In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind."
                  icon="/img/products/trade.svg"
                  buttonText="button"
                  className={[
                    "delay-100 duration-1000",
                    scrollTop > 300
                      ? "mb-0 mt-0 opacity-1"
                      : "mt-20 -mb-20 opacity-0",
                  ].join(" ")}
                />
                <Card
                  title="Card"
                  text="In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind."
                  icon="/img/products/farm.svg"
                  buttonText="button"
                  className={[
                    "delay-300 duration-1000",
                    scrollTop > 300
                      ? "mb-0 mt-0 opacity-1"
                      : "mt-20 -mb-20 opacity-0",
                  ].join(" ")}
                />
                <Card
                  title="Card"
                  text="In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind."
                  icon="/img/products/api.svg"
                  buttonText="button"
                  className={[
                    "delay-100 duration-1000",
                    scrollTop > 500
                      ? "mb-0 mt-0 opacity-1"
                      : "mt-20 -mb-20 opacity-0",
                  ].join(" ")}
                />
                <Card
                  title="Card"
                  text="In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind."
                  icon="/img/products/token.svg"
                  buttonText="button"
                  className={[
                    "delay-300 duration-1000",
                    scrollTop > 500
                      ? "mb-0 mt-0 opacity-1"
                      : "mt-20 -mb-20 opacity-0",
                  ].join(" ")}
                />
              </div>

              <div className="text-white text-3xl mt-12">
                WE BELIEVE IN THE POTENTIAL OF FAST &amp; FEELESS BLOCKCHAIN
                &amp; ARE READY TO PRESENT THE UNIFIED ECOSYSTEM BUILT ON
                Casper→SO #JOINTHECASPER
              </div>
            </div>

            <div className="section-3 text-white">
              <div className="text-3xl font-black mb-12">Why Casper</div>
              <div className="grid grid-cols-2 gap-6">
                <div className="flex flex-col space-y-6">
                  <div className="text-xl font-bold mb-6">Casper</div>
                  <FeatureItem
                    className={[
                      "duration-1000 delay-100",
                      scrollTop > 1400 ? "ml-0 opacity-1" : "-ml-20 opacity-0",
                    ].join(" ")}
                  >
                    Secure and scalable
                  </FeatureItem>
                  <FeatureItem
                    className={[
                      "duration-1000 delay-300",
                      scrollTop > 1400 ? "ml-0 opacity-1" : "-ml-20 opacity-0",
                    ].join(" ")}
                  >
                    Secure and scalable
                  </FeatureItem>
                  <FeatureItem
                    className={[
                      "duration-1000 delay-500",
                      scrollTop > 1400 ? "ml-0 opacity-1" : "-ml-20 opacity-0",
                    ].join(" ")}
                  >
                    Secure and scalable
                  </FeatureItem>
                  <FeatureItem
                    className={[
                      "duration-1000 delay-700",
                      scrollTop > 1400 ? "ml-0 opacity-1" : "-ml-20 opacity-0",
                    ].join(" ")}
                  >
                    Secure and scalable
                  </FeatureItem>
                </div>

                <div className="flex flex-col space-y-6">
                  <div className="text-xl font-bold mb-6">Others</div>
                  <OtherFeatureItem
                    className={[
                      "duration-1000 delay-900",
                      scrollTop > 1400 ? "ml-0 opacity-1" : "-ml-20 opacity-0",
                    ].join(" ")}
                  >
                    Secure and scalable
                  </OtherFeatureItem>
                  <OtherFeatureItem
                    className={[
                      "duration-1000 delay-1100",
                      scrollTop > 1400 ? "ml-0 opacity-1" : "-ml-20 opacity-0",
                    ].join(" ")}
                  >
                    Secure and scalable
                  </OtherFeatureItem>
                  <OtherFeatureItem
                    className={[
                      "duration-1000 delay-1300",
                      scrollTop > 1400 ? "ml-0 opacity-1" : "-ml-20 opacity-0",
                    ].join(" ")}
                  >
                    Secure and scalable
                  </OtherFeatureItem>
                  <OtherFeatureItem
                    className={[
                      "duration-1000 delay-1500",
                      scrollTop > 1400 ? "ml-0 opacity-1" : "-ml-20 opacity-0",
                    ].join(" ")}
                  >
                    Secure and scalable
                  </OtherFeatureItem>
                </div>
              </div>
            </div>

            <div className="section-4 flex flex-col space-y-12">
              <Product
                direction="left"
                image="/img/products/thumbnail.svg"
                title="Casper Tracker"
                text="In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind."
                buttonText="Go to Tracker"
                classNameImage={[
                  "delay-100 duration-1000",
                  scrollTop > 1800
                    ? "mb-0 mt-0 opacity-1"
                    : "mt-30 -mb-30 opacity-0",
                ].join(" ")}
                classNameDesc={[
                  "delay-300 duration-1000",
                  scrollTop > 1800
                    ? "mb-0 mt-0 opacity-1"
                    : "mt-30 -mb-30 opacity-0",
                ].join(" ")}
              />
              <Product
                direction="right"
                image="/img/products/thumbnail.svg"
                title="Casper Farm"
                text="In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind."
                buttonText="Go to Farm"
                classNameImage={[
                  "delay-500 duration-1000",
                  scrollTop > 2200
                    ? "mb-0 mt-0 opacity-1"
                    : "mt-30 -mb-30 opacity-0",
                ].join(" ")}
                classNameDesc={[
                  "delay-700 duration-1000",
                  scrollTop > 2200
                    ? "mb-0 mt-0 opacity-1"
                    : "mt-30 -mb-30 opacity-0",
                ].join(" ")}
              />
              <Product
                direction="left"
                image="/img/products/thumbnail.svg"
                title="Casper Api"
                text="In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind."
                buttonText="Go to Api"
                classNameImage={[
                  "delay-500 duration-1000",
                  scrollTop > 2600
                    ? "mb-0 mt-0 opacity-1"
                    : "mt-30 -mb-30 opacity-0",
                ].join(" ")}
                classNameDesc={[
                  "delay-700 duration-1000",
                  scrollTop > 2600
                    ? "mb-0 mt-0 opacity-1"
                    : "mt-30 -mb-30 opacity-0",
                ].join(" ")}
              />
              <Product
                direction="right"
                image="/img/products/thumbnail.svg"
                title="Casper Token"
                text="In search for cute little puppy, Captain Sem has come back from his tragic death. With his hogwarts certified power he promise to be a hero for all of ghostkind."
                buttonText="Go to Token"
                classNameImage={[
                  "delay-500 duration-1000",
                  scrollTop > 3000
                    ? "mb-0 mt-0 opacity-1"
                    : "mt-30 -mb-30 opacity-0",
                ].join(" ")}
                classNameDesc={[
                  "delay-700 duration-1000",
                  scrollTop > 3000
                    ? "mb-0 mt-0 opacity-1"
                    : "mt-30 -mb-30 opacity-0",
                ].join(" ")}
              />
            </div>
          </div>

          <Footer />
        </Container>
      </div>
    </div>
  );
};

export default Index;
